# Generated by Django 3.0.7 on 2020-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.TextField(blank=True, help_text='This field with a link to the small size photo for users downloaded from a third-party API', null=True, verbose_name='Small')),
                ('small_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Small img')),
                ('large', models.TextField(blank=True, help_text='This field with a link to the large size photo for users downloaded from a third-party API', null=True, verbose_name='Large')),
                ('large_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Large img')),
            ],
        ),
    ]
